### ISSUE TITLE
Need Help

### ISSUE THREAD

**Issue by notnotrachit** [elit-altum/Cryptic-Hunt#1]
Hey, I was trying to set this up & require some help. Can you help me? And if you are on other platforms(discord/telegram)  then it would be better.

**Comment by notnotrachit** [comment]
@elit-altum

**Comment by elit-altum** [comment]
Sure! How can I help? As this is an open source project, let's keep the discussion here only.

**Comment by notnotrachit** [comment]
> Sure! How can I help? As this is an open source project, let's keep the discussion here only.

I don't have any problem here, but its not that convenient, anyway if you want it here then fine. 

So basically I  set it up on my local machine. But I can't figure out how to create accounts. And how to create admin account?

(P.S. I am not a web developer, I just know python, html, css and understand some js)

**Comment by elit-altum** [comment]
@rachit1601 I have updated the README.md Please check if that can help!

**Comment by notnotrachit** [comment]
> @rachit1601 I have updated the README.md Please check if that can help!

@elit-altum thanks for updating it, but I am facing few issues:
\>`secretorPrivateKey must have a value` while signing up or logging in
So I'm now able to login. I think this is also cause as it didn't import .env for some reason
\>And I entered the mongo db srv in .env file but it gave me an error. When I put it directly in app.js, it runs fine. 

And thanks for helping

**Comment by notnotrachit** [comment]
Ohh , lol, i fixed it, it was a naming issue of .env file

**Comment by notnotrachit** [comment]
Thanks a lot

**Comment by notnotrachit** [comment]
Hey, 2 more questions please, 
* If I make the signup page available to everyone, then will it be fine, or there could be some security issues?
* Is it easy to add oauth2 for login and signup? If yes then tell me, I will try to add that. If its difficult then leave it.

**Comment by elit-altum** [comment]
No there won't be security issue. And yes you can try oauth, I have never worked with it so I don't know much about it.
